// EQUIPMENT reducer types
export const EQUIPMENTS_TYPE = {
    SET_EQUIPMENTS: 'EQUIPMENTS_TYPE::SET_EQUIPMENTS',
    SET_END_EQUIPMENTS: 'EQUIPMENTS_TYPE::SET_END_EQUIPMENTS', // end of equipments list, could not load more
    ADD_MORE_EQUIPMENTS: 'EQUIPMENTS_TYPE::ADD_MORE_EQUIPMENTS', //add more equipment data

    LOADING: 'EQUIPMENTS_TYPE::LOADING',
    LOADED: 'EQUIPMENTS_TYPE::LOADED',
    // Saga
    GET_EQUIPMENTS: 'EQUIPMENTS_TYPE::GET_EQUIPMENTS',
    //
    SET_EQUIPMENT_FILTER: 'EQUIPMENTS_TYPE::SET_EQUIPMENT_FILTER',
    SET_SEARCH_EQUIPMENTS: 'EQUIPMENTS_TYPE::SET_SEARCH_EQUIPMENTS',
    GET_SEARCH_EQUIPMENTS: 'EQUIPMENTS_TYPE::GET_SEARCH_EQUIPMENTS',
};

export const EQUIPMENT_TYPE = {
    GET_EQUIPMENT_BY_ID: 'EQUIPMENT_TYPE::GET_EQUIPMENT_BY_ID',
    SET_EQUIPMENT: 'EQUIPMENT_TYPE::SET_EQUIPMENT',
    LOADING_EQUIPMENT: 'EQUIPMENT_TYPE::LOADING_EQUIPMENT',
    LOADED_EQUIPMENT: 'EQUIPMENT_TYPE::LOADED_EQUIPMENT',
};

export const SEARCH_TYPE = {
    LOADING_SEARCH: 'SEARCH_TYPE::LOADING_SEARCH',
    SET_QUERY: 'SEARCH_TYPE::SET_QUERY',
    SET_FILTERS: 'SEARCH_TYPE::SET_FILTERS',
};

export const UI_TYPE = {
    SET_LOADING_AUTHEN: 'UI_TYPE::SET_LOADING_AUTHEN',
    SET_LOADING_CREATE_EQUIPMENT: 'UI_TYPE::SET_LOADING_CREATE_EQUIPMENT',
    SET_LOADING_EDIT_EQUIPMENT: 'UI_TYPE::SET_LOADING_EDIT_EQUIPMENT',
    SET_LOADING_DELETE_EQUIPMENT: 'UI_TYPE::SET_LOADING_DELETE_EQUIPMENT',
    SET_ERROR: 'UI_TYPE::SET_ERROR',
};

export const RESPONSIVE_TYPE = {
    SET_MOBILE_MODE: 'RESPONSIVE_TYPE::SET_MOBILE_MODE',
};
